lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views  #1
from lists import urls as list_urls  #2

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^home', list_views.todo_list, name='todo_list'),
    url(r'^blog', list_views.blog, name='blog'),
    url(r'^lists/', include(list_urls)),
    # url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class List(models.Model):
	def get_absolute_url(self):
		return reverse('view_list', args=[self.id])

class Item(models.Model):
	text = models.TextField(default='')
	list = models.ForeignKey(List, default=None)

lists/views.py
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import redirect, render
from lists.models import Item, List

# Create your views here.
def home_page(request):
    #if request.method == 'POST':
    #    Item.objects.create(text=request.POST['item_text'])
    #    return redirect('/lists/the-only-list-in-the-world/')

    #items = Item.objects.all()
    #countsItem = Item.objects.count()
    #comment = 'yey, waktunya berlibur'

    #return render(request, 'index.html')
    countsItem = Item.objects.count()
    comment = 'yey, waktunya berlibur'

    return render(request, 'home.html', {'comment': comment})

def todo_list(request):
    #if request.method == 'POST':
    #    Item.objects.create(text=request.POST['item_text'])
    #    return redirect('/lists/the-only-list-in-the-world/')

    #items = Item.objects.all()
    #countsItem = Item.objects.count()
    #comment = 'yey, waktunya berlibur'

    #return render(request, 'index.html')
    countsItem = Item.objects.count()
    comment = 'yey, waktunya berlibur'

    return render(request, 'home.html', {'comment': comment})

def blog(request):
    # countsItem = Item.objects.count()
    # comment = 'yey, waktunya berlibur'

    # return render(request, 'home.html', {'comment': comment})
    return render(request, 'index.html')

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    error = None

    comment = ''
    countList = Item.objects.filter(list_id=list_.id).count()
    if countList == 0:
        comment = 'yey, waktunya berlibur'
    elif (countList > 0) and (countList < 5):
        comment = 'sibuk tapi santai'
    else:
        comment = 'oh tidak'

    if request.method == 'POST':
        try:
            item = Item(text=request.POST['item_text'], list=list_)
            item.full_clean()
            item.save()
            return redirect(list_)
        except ValidationError:
            error = "You can't have an empty list item"
    return render(request, 'list.html', {'list': list_, 'error': error, 'comment': comment})

def new_list(request):
    list_ = List.objects.create()
    item = Item(text=request.POST['item_text'], list=list_)
    try:
        item.full_clean()
        item.save()
    except ValidationError:
        list_.delete()
        error = "You can't have an empty list item"
        return render(request, 'home.html', {"error": error})
    return redirect(list_)

lists/templates/base.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>To-Do lists</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/base.css" rel="stylesheet">
	</head>
	<body>
		<header id="top" class="header">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 jumbotron">
					<div class="text-center">
						<h1>{% block header_text %}{% endblock %}</h1>
						<form method="POST" action="{% block form_action %}{% endblock %}">
							<input name="item_text" id="id_new_item" class="form-control input-lg" placeholder="Enter a to-do item" />{% csrf_token %}
							{% if error %}
							<div class="form-group has-error">
								<span class="help-block">{{ error }}</span>
							</div>
							{% endif %}
						</form>

						{{ comment }}

					</div>
					<center><a href="/blog" class="btn btn-dark btn-lg"><button type="button" class="btn btn-default"><i class="glyphicon glyphicon-home"></i> Go To Blog</button></a></center>
				</div>

			</div>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					{% block table %}
					{% endblock %}
				</div>
			</div>
		</div>
		</header>
	</body>
</html>

lists/templates/base_buruk.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>To-Do lists</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/base_buruk.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-2 col-md-offset-2 jumbotron">
					<div class="text-center">
						<h1>{% block header_text %}{% endblock %}</h1>
						<form method="POST" action="{% block form_action %}{% endblock %}">
							<input name="item_text" id="id_new_item"
							class="form-control input-lg"
							placeholder="Enter a to-do item"
							/>
							{% csrf_token %}
						</form>

						{{ comment }}

					</div>
				</div>
			</div>



			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					{% block table %}
					{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html>

lists/templates/home.html
<html>
	<head>
		<title>To-Do lists</title>
	</head>
	<body>
		{% extends 'base.html' %}
		<h1>{% block header_text %}Start a new To-Do list{% endblock %}</h1>
		<form method="POST" action="{% block form_action %}{% url 'new_list' %}{% endblock %}">
			<input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
			{% csrf_token %}
		</form>
	</body>
</html>

lists/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Stylish Portfolio - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="static/bootstrap/css/stylish-portfolio.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="static/bootstrap/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <a href="#top"  onclick = $("#menu-close").click(); >Menu</a>
            </li>
            <li>
                <a href="#top" onclick = $("#menu-close").click(); >Home</a>
            </li>
            <li>
                <a href="#about" onclick = $("#menu-close").click(); >About</a>
            </li>
            <!-- <li>
                <a href="#services" onclick = $("#menu-close").click(); >Services</a>
            </li>
            <li>
                <a href="#portfolio" onclick = $("#menu-close").click(); >Portfolio</a>
            </li>
            <li>
                <a href="#contact" onclick = $("#menu-close").click(); >Contact</a>
            </li> -->
        </ul>
    </nav>

    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>Set your goals</h1>
            <h3>Start your journey</h3>
            <br>
            <a href="#about" class="btn btn-dark btn-lg">Find Out More</a>
        </div>
    </header>

    <!-- About -->
    <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Ayu Sahnaz Ovariyanti</h2>
                    <p class="lead">Computer Science 2012</p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Callout -->
    <aside class="callout">
        <div class="text-vertical-center">
            <h1><a href="/home" class="btn btn-dark btn-lg">Write your to-do lists!</a></h1>
        </div>
    </aside>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>Contact Me</strong>
                    </h4>
                    <p>Fakultas Ilmu Komputer<br>Universitas Indonesia</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i>08881745897</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:name@example.com">ayusahnaz@ui.ac.id</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; Penjaminan Mutu Perangkat Lunak 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="static/bootstrap/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="static/bootstrap/js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    </script>

</body>

</html>

lists/templates/list.html
<html>
	<head>
		<title>To-Do lists</title>
	</head>
	<body>
		{% extends 'base.html' %}
		<h1>{% block header_text %}Your To-Do list{% endblock %}</h1>
		<form method="POST" action="{% block form_action %}{% url 'view_list' list.id %}{% endblock %}">
			<input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
			{% csrf_token %}
		</form>

		<span>{{ comment }}</span>

		{% block table %}
		<table id="id_list_table" class="table">
			{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
			{% endfor %}
		</table>
		{% endblock %}
	</body>
</html>